id: P007115
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS139873
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་མཛེས་རྩལ་ལས་བྲིས་བུར་གཉིས་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ།
  author: ''
  volumes:
    4b7b337b3efb4e4db734b99f87353db8:
      image_group_id: I1KG1613
      title: ''
      volume_number: 1
      total_pages: 606
ebook_metadata:
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་མཛེས་རྩལ་ལས་བྲིས་བུར་གཉིས་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ།
  author: ''
  sku: P007115
  cover: cover.jpg
  layers:
  - pagination
