id: P007115
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:42:40.967671
source_metadata:
  id: bdr:W1GS139873
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་མཛེས་རྩལ་ལས་བྲིས་བུར་གཉིས་ཀྱི་བྱུང་བ་མདོ་ཙམ་བརྗོད་པ།
  author: ''
  volumes:
    7c6d9628f1e44c31a7919ef6a430f243:
      image_group_id: I1KG1613
      title: Volume 1 of bod kyi srol rgyun mdzes rtsal las bris bur gnyis kyi byung
        ba mdo tsam brjod pa
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
